#!/bin/sh

set -eu -o pipefail # fail on error , debug all lines

sudo -n true
test $? -eq 0 || exit 1 "you should have sudo privilege to run this script"

apt-get update  # To get the latest package lists
apt-get install exa -y
apt-get install command-not-found -y